shadow dom is optional via attribute presence
notwaldorf/lazy-image pull request #7
Opened 2018-02-01 04:35 UTC by argyleink

made an api for what was optional via commented code 👍

2018-02-05 22:04 UTC, notwaldorf commented
This is cool! Unfortunately this reverses the _current_ behaviour of the element, thus forcing everyone to update (if they want to maintain the status quo). What to you think about naming renaming the attribute to `as-decorator`, and reversing the if statement? (if `as-decorator` is present, then don't use a shadow root)

2018-02-05 22:08 UTC, argyleink commented
works for me! you'll find the PR updated for your review

2018-02-05 22:13 UTC, notwaldorf requested changes

2018-02-05 22:13 UTC, notwaldorf commented on lazy-image.js
> +    if (!this.hasAttribute('shadow')) {
This is the same as your previous change (the user still has to put the `shadow` attribute for the status quo to work. I meant:
```
if (this.hasAttribute('as-decorator') {
  this.appendChild(this._img);
} else {
  const shadow = this.attachShadow({mode: 'open'});
  shadow.appendChild(this._img);
}
```

2018-02-06 01:46 UTC, argyleink commented on lazy-image.js
> +    if (!this.hasAttribute('shadow')) {
you're right! i only did half the changes requested.. i should have spent the time in my updated PR earlier, i totally rushed it and forgot half the comments you made. sorry! will update shortly!

2018-02-06 01:53 UTC, argyleink reviewed
ready for review!

2018-02-14 19:21 UTC, notwaldorf approved these changes

2018-02-14 19:21 UTC, notwaldorf commented
Perfect, thanks!

2018-02-14 19:21 UTC, merged